### PR TITLE
V8 inspector and error handling fixes

### LINKED ISSUE #21: V8 inspector agent crashes on shutdown after attaching debugger when running unit tests
**Describe the bug**
The unit tests crash on shutdown after attaching a debugger (e.g., with ChromeDevTools).

**To Reproduce**
1. Set `waitForDebugger` to `true` in `tests.js`.
2. Run the unit tests.
3. Attach the V8 debugger using Chrome `about://inspect`.
4. Continue when the `debugger;` statement hits.
5. Unit tests crashes after completing the tests

**Call Stack**
```
<unknown> 0x000071421b6815bf
<unknown> 0x000071421b6837bd
<unknown> 0x000071421b683a29
std::__ndk1::default_delete::operator()(v8_inspector::V8InspectorSession *) const memory:2338
std::__ndk1::unique_ptr::reset(v8_inspector::V8InspectorSession *) memory:2593
std::__ndk1::unique_ptr::~unique_ptr() memory:2547
Babylon::V8NodeInspector::~V8NodeInspector() V8InspectorAgent.cpp:183
Babylon::V8NodeInspector::~V8NodeInspector() V8InspectorAgent.cpp:183
std::__ndk1::default_delete::operator()(Babylon::V8NodeInspector *) const memory:2338
std::__ndk1::unique_ptr::reset(Babylon::V8NodeInspector *) memory:2593
Babylon::AgentImpl::Stop() V8InspectorAgent.cpp:417
Babylon::V8InspectorAgent::stop() V8InspectorAgent.cpp:667
Babylon::AppRuntime::RunEnvironmentTier(const char *) AppRuntime_V8.cpp:91
Babylon::AppRuntime::RunPlatformTier() AppRuntime_Android.cpp:10
$_1::operator()() const AppRuntime.cpp:12
decltype(std::__ndk1::forward<Babylon::AppRuntime::AppRuntime(std::__ndk1::function<void (std::exception const&)>)::$_1&>(fp)()) std::__ndk1::__invoke<Babylon::AppRuntime::AppRuntime(std::__ndk1::function<void (std::exception const&)>)::$_1&>(Babylon::AppRuntime::AppRuntime(std::__ndk1::function<void (std::exception const&)>)::$_1&) type_traits:3501
std::__ndk1::__invoke_void_return_wrapper::__call<…>($_1 &) __functional_base:348
std::__ndk1::__function::__alloc_func::operator()() functional:1540
std::__ndk1::__function::__func::operator()() functional:1714
std::__ndk1::__function::__value_func::operator()() const functional:1867
std::__ndk1::function::operator()() const functional:2473
decltype(std::__ndk1::forward<std::__ndk1::function<void ()> >(fp)()) std::__ndk1::__invoke<std::__ndk1::function<void ()> >(std::__ndk1::function<void ()>&&) type_traits:3501
std::__ndk1::__thread_execute<…>(std::__ndk1::tuple<…> &, std::__ndk1::__tuple_indices<…>) thread:273
std::__ndk1::__thread_proxy<…>(void *) thread:283
__pthread_start(void *) 0x00007142b5480f3c
__start_thread 0x00007142b542fc8e
__bionic_clone 0x00007142b542e516
```

**Expected behavior**
The unit tests to exit cleanly.

**Other**
 - Platform: Android

### LINKED ISSUE #61: When using UWP and V8, V8 debugging doesn't work
When building against UWP, while using V8, V8 debugging will not work.  The projects will still build as long as the `JSRUNTIMEHOST_CORE_APPRUNTIME_V8_INSPECTOR` is disabled when the initial `cmake` project files are built.

### PR DESCRIPTION
**Pull request by bghgary**
- Remove dead code in V8 inspector
- Fix race condition on V8 inspector shutdown
- Add options struct to AppRuntime to support new WaitForDebugger flag
- Use new WaitForDebugger flag in JavaScript tests
- Remove newline from console log callback

Fixes #21
Fixes #61

### CODE REVIEW

File: Tests/UnitTests/Android/app/src/androidTest/java/com/jsruntimehost/unittests/Main.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
  */
 @RunWith(AndroidJUnit4.class)
 public class Main {
-    @Test
+    @Test(timeout = 3600000)
```
Comment (bghgary) [inline Tests/UnitTests/Android/app/src/androidTest/java/com/jsruntimehost/unittests/Main.java:20]:
```suggestion
    @Test
```

**Review by SergioRZMasson — APPROVED** [review]
LGTM
